In [1]:
#library imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
import talib
import warnings
from matplotlib.pyplot import figure
warnings.filterwarnings('ignore')

In [75]:
#data imports
volumes = pd.read_csv('../Data/stock_volumes.csv', index_col = 'date', parse_dates = True)
prices = pd.read_csv('../Data/stock_prices.csv', index_col = 'date', parse_dates = True)
info = pd.read_csv('../Data/stock_info.csv', index_col = 'Instrument')
sp_listings = pd.read_csv('../Data/sp500_listings.csv', index_col = 'date', parse_dates = True)

In [77]:
#drop stocks (columns) with all missing values
drop_columns = []

for col in prices.columns:
    if prices[col].isnull().all() == True:
        drop_columns.append(col)

prices = prices.drop(columns = drop_columns)

In [92]:
#calculate returns
prices_r = prices.copy(deep = True)
prices_r = prices_r.pct_change()*100

In [93]:
for col in prices_r.columns:
    #select the stock
    stock = prices_r[[col]]
    
    #if stock is not currently listed as active
    if info.loc[col,:]['ESTAT'] != 'ACT.':
        #find delist date
        delist_date = sp_listings.where(sp_listings['stock'] == col).last_valid_index() + pd.DateOffset(1)
        #set all values after delist date to NaN
        stock.loc[delist_date:][col] = np.nan
        #replace in original dataframe
        prices_r[col] = stock[col]

In [94]:
prices_r

,905270,921795,904261,905261,916328,923024,936365,902355,912215,929813,...,9660J1,69568X,543755,77463M,29235J,131745,69487D,68157P,9110RA,292703
date,,,,,,,,,,,,,,,,,,,,,
1990-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-03,-0.835165,-0.475059,5.000000,-0.810537,0.361421,0.000000,-3.030303,0.000000,-0.431034,-1.315789,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,-0.797872,-1.272872,2.380952,-1.634321,-0.180060,3.454545,-1.562500,0.530612,0.225108,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,-2.546917,1.531023,-0.372093,-1.661475,-1.079730,1.054482,-3.174603,0.487211,-0.656531,-1.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,2.017423,-0.873016,0.000000,2.534319,0.000000,0.000000,0.000000,1.010101,0.434783,3.405405,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-24,NaN,NaN,NaN,NaN,0.136600,NaN,0.349877,NaN,NaN,NaN,...,0.376702,4.400221,1.590198,-0.991004,1.682900,3.364703,2.271817,0.634962,4.859794,1.204016
2021-05-25,NaN,NaN,NaN,NaN,0.946372,NaN,0.542355,NaN,NaN,NaN,...,0.230947,-0.288569,0.449063,-1.661106,0.439588,-0.548765,0.185928,0.727530,1.884279,-0.498203
2021-05-26,NaN,NaN,NaN,NaN,-1.393581,NaN,0.616491,NaN,NaN,NaN,...,1.296083,2.388001,-0.166049,3.255613,2.317760,4.702784,0.673960,2.336242,-0.429666,-1.520393
2021-05-27,NaN,NaN,NaN,NaN,-0.907923,NaN,0.102119,NaN,NaN,NaN,...,0.056867,1.893011,-0.063971,-0.510347,1.044185,-0.275482,1.979237,1.876893,1.247655,2.369727
2021-05-28,NaN,NaN,NaN,NaN,0.829804,NaN,2.116807,NaN,NaN,NaN,...,-0.312589,-0.892462,-0.409679,0.519992,0.160551,-1.549363,0.570831,0.766354,-0.444733,1.742926

In [95]:
#save
prices_r.to_pickle('../Data/returns.pkl')